apiVersion: v1
kind: ServiceAccount
metadata:
  name: encrypted-volume-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: encrypted-volume-operator
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      ["pods", "pods/log", "pods/exec", "persistentvolumeclaims", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["crypto.example.com"]
    resources: ["encryptedvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: encrypted-volume-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: encrypted-volume-operator
subjects:
  - kind: ServiceAccount
    name: encrypted-volume-operator
    namespace: default
