{{- if .Values.imageCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imageCredentials.dockerConfigJson | quote }}
{{- end }}