apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "luks-csi-driver.controllerServiceAccount" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "luks-csi-driver.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "luks-csi-driver.nodeServiceAccount" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "luks-csi-driver.labels" . | nindent 4 }}
